[whizard2]
Version = key4hep_260408

[ddsim]
SteeringFile = cld_steer.py
ExtraCLIArguments= --vertexSigma 0.0098 2.54e-5 0.646 0.0063 --physics.rejectPDGs 1,2,3,4,5,6,12,14,16,21,23,24,25

[gaudiapp]
ExecutableName = k4run
SteeringFile = CLDReconstruction.py
InputFileFlag = --inputFiles
OutputFileFlag = --IOSvc.Output
Arguments = --cms 240

[Production Parameters]
machine = ee
prodGroup = fcc_ee_spring2024_ZH_xsection

softwareVersion = key4hep_260408
generatorApplication = whizard2
simulationApplication = ddsim
reconstructionApplication = gaudiapp
generatorSteeringFile = wzp6_ee_mumuH_ecm240.sin

configVersion = cld-r2025-11-07
configPackage = fccConfig
eventsPerJobs = 1000

numberOfTasks = 1

campaign = test_spring2024
energies = 240
processes = ee_mumuH
detectorModel = CLD_o2_v08
additionalName = ZH_xsection
productionLogLevel = VERBOSE
outputSE = CERN-DST-EOS

finalOutputSE = CERN-SRM
MoveStatus = Stopped
MoveGroupSize = 10

ProdTypes = Gen, Sim, Rec
