[whizard2]
Version = 2.8.3

[ddsim]
SteeringFile = cld_steer.py
ExtraCLIArguments= --vertexSigma 0.0098 2.54e-5 0.646 0.0063 --physics.rejectPDGs 1,2,3,4,5,6,12,14,16,21,23,24,25

[gaudiapp]
ExecutableName = k4run
SteeringFile = CLDReconstruction.py
InputFileFlag = --inputFiles
OutputFileFlag = --IOSvc.Output
Arguments = --cms 240

[Production Parameters]
machine = ee
prodGroup = fcc_ee_spring2024_ZH_xsection_ee_xx

softwareVersion = key4hep_250128
generatorApplication = whizard2
simulationApplication = ddsim
reconstructionApplication = gaudiapp
generatorSteeringFile = wzp6_ee_mumu_ecm240.sin, wzp6_ee_tautau_ecm240.sin

configVersion = key4hep-devel-6
configPackage = fccConfig
eventsPerJobs = 1000, 1000

numberOfTasks = 1, 1

campaign = test_spring2024
energies = 240, 240
processes = ee_xx
detectorModel = CLD_o2_v07
additionalName = ZH_xsection_3
productionLogLevel = VERBOSE
outputSE = CERN-DST-EOS

finalOutputSE = CERN-SRM
MoveStatus = Stopped
MoveGroupSize = 10

ProdTypes = Gen, Sim, Rec
