[gaudiapp_gen]
ExecutableName = k4run
SteeringFile = k4_pythia8.py
OutputFileFlag = --HepMCFileWriter.Filename

[ddsim]
SteeringFile = cld_steer.py
ExtraCLIArguments= --vertexSigma 0.0098 2.54e-5 0.646 0.0063 --physics.rejectPDGs 1,2,3,4,5,6,12,14,16,21,23,24,25

[gaudiapp_rec]
ExecutableName = k4run
SteeringFile = CLDReconstruction.py
InputFileFlag = --inputFiles
OutputFileFlag = --IOSvc.Output
Arguments = --cms 240

[Production Parameters]
machine = ee

campaign = test_spring2024
prodGroup = fcc_ee_spring2024_ZH_xsection
additionalName = ZH_xsection

generatorApplication = gaudiapp_gen
simulationApplication = ddsim
reconstructionApplication = gaudiapp_rec

softwareVersion = key4hep_260408
configPackage = fccConfig
configVersion = cld-r2025-11-07

eventsPerJobs = 1000
numberOfTasks = 1

energies = 240
processes = ee_ZZ
generatorSteeringFile = p8_ee_ZZ_ecm240.cmd

detectorModel = CLD_o2_v08

productionLogLevel = VERBOSE
outputSE = CERN-DST-EOS
finalOutputSE = CERN-SRM
MoveStatus = Stopped
MoveGroupSize = 10

ProdTypes = Gen, Sim, Rec
